"""add all new models with reference tables again

Revision ID: abbf0934e740
Revises: 
Create Date: 2026-03-11 12:50:30.396047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbf0934e740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_jenis_kolaborator',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_jenis_sampah',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_kategori_artikel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_kategori_aset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_kategori_barang',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('artikel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_penulis', sa.String(length=36), nullable=False),
    sa.Column('judul_artikel', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('kategori_id', sa.String(length=36), nullable=False),
    sa.Column('konten_teks', sa.Text(), nullable=True),
    sa.Column('foto_cover_url', sa.String(length=500), nullable=True),
    sa.Column('status_publikasi', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='statuspublikasi'), nullable=False),
    sa.Column('jumlah_views', sa.Integer(), nullable=False),
    sa.Column('waktu_publish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_penulis'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['ref_kategori_artikel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artikel_id_penulis'), ['id_penulis'], unique=False)
        batch_op.create_index(batch_op.f('ix_artikel_kategori_id'), ['kategori_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artikel_slug'), ['slug'], unique=True)

    op.create_table('aset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('nama_aset', sa.String(length=200), nullable=False),
    sa.Column('kategori_aset_id', sa.String(length=36), nullable=False),
    sa.Column('deskripsi_aset', sa.Text(), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=False),
    sa.Column('kabupaten_kota', sa.String(length=100), nullable=True),
    sa.Column('alamat_lengkap', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('penanggung_jawab', sa.String(length=100), nullable=True),
    sa.Column('kontak', sa.String(length=20), nullable=True),
    sa.Column('pictures_urls', sa.JSON(), nullable=True),
    sa.Column('status_verifikasi', sa.Enum('MENUNGGU', 'TERVERIFIKASI', 'DITOLAK', name='statusverifikasiaset'), nullable=False),
    sa.Column('id_admin_verifikator', sa.String(length=36), nullable=True),
    sa.Column('catatan_verifikasi', sa.Text(), nullable=True),
    sa.Column('waktu_verifikasi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_admin_verifikator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_aset_id'], ['ref_kategori_aset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aset_id_user'), ['id_user'], unique=False)
        batch_op.create_index(batch_op.f('ix_aset_kategori_aset_id'), ['kategori_aset_id'], unique=False)

    op.create_table('kolaborator',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('nama_organisasi', sa.String(length=100), nullable=False),
    sa.Column('jenis_kolaborator_id', sa.String(length=36), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('kabupaten_kota', sa.String(length=100), nullable=True),
    sa.Column('alamat_lengkap', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('penanggung_jawab', sa.String(length=100), nullable=True),
    sa.Column('kontak', sa.String(length=20), nullable=True),
    sa.Column('sosmed', sa.String(length=500), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=False),
    sa.Column('status_verifikasi', sa.Enum('MENUNGGU', 'TERVERIFIKASI', 'DITOLAK', name='statusverifikasikolaborator'), nullable=False),
    sa.Column('id_admin_verifikator', sa.String(length=36), nullable=True),
    sa.Column('catatan_verifikasi', sa.Text(), nullable=True),
    sa.Column('waktu_verifikasi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_admin_verifikator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jenis_kolaborator_id'], ['ref_jenis_kolaborator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kolaborator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kolaborator_id_user'), ['id_user'], unique=False)
        batch_op.create_index(batch_op.f('ix_kolaborator_jenis_kolaborator_id'), ['jenis_kolaborator_id'], unique=False)

    op.create_table('laporan_sampah_ilegal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_warga', sa.String(length=36), nullable=False),
    sa.Column('foto_bukti_urls', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('kabupaten_kota', sa.String(length=100), nullable=True),
    sa.Column('alamat_lokasi', sa.Text(), nullable=True),
    sa.Column('jenis_sampah_id', sa.String(length=36), nullable=False),
    sa.Column('estimasi_berat_kg', sa.Float(), nullable=True),
    sa.Column('karakteristik', sa.Enum('BISA_DIDAUR_ULANG', 'RESIDU', name='karakteristik'), nullable=True),
    sa.Column('bentuk_timbulan', sa.Enum('TERCECER', 'MENUMPUK', name='bentuktimbulan'), nullable=True),
    sa.Column('deskripsi_laporan', sa.Text(), nullable=True),
    sa.Column('status_laporan', sa.Enum('MENUNGGU', 'DITERIMA', 'DITOLAK', 'DITINDAK', 'SELESAI', name='statuslaporan'), nullable=False),
    sa.Column('id_admin_verifikator', sa.String(length=36), nullable=True),
    sa.Column('catatan_verifikasi', sa.Text(), nullable=True),
    sa.Column('waktu_verifikasi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_admin_verifikator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_warga'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jenis_sampah_id'], ['ref_jenis_sampah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laporan_sampah_ilegal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laporan_sampah_ilegal_id_warga'), ['id_warga'], unique=False)
        batch_op.create_index(batch_op.f('ix_laporan_sampah_ilegal_jenis_sampah_id'), ['jenis_sampah_id'], unique=False)

    op.create_table('marketplace_daur_ulang',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_penjual', sa.String(length=36), nullable=False),
    sa.Column('nama_barang', sa.String(length=150), nullable=False),
    sa.Column('kategori_barang_id', sa.String(length=36), nullable=False),
    sa.Column('deskripsi_barang', sa.Text(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('berat_estimasi_kg', sa.Float(), nullable=True),
    sa.Column('kondisi', sa.Enum('LAYAK_PAKAI', 'BUTUH_PERBAIKAN', 'RONGSOKAN', name='kondisibarang'), nullable=False),
    sa.Column('foto_barang_urls', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('kabupaten_kota', sa.String(length=100), nullable=True),
    sa.Column('alamat_lengkap', sa.Text(), nullable=True),
    sa.Column('status_ketersediaan', sa.Enum('TERSEDIA', 'DIPESAN', 'TERJUAL', name='statusketersediaan'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_penjual'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_barang_id'], ['ref_kategori_barang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_daur_ulang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_daur_ulang_id_penjual'), ['id_penjual'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_daur_ulang_kategori_barang_id'), ['kategori_barang_id'], unique=False)

    op.create_table('artikel_komentar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_artikel', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('isi_komentar', sa.Text(), nullable=False),
    sa.Column('status_komentar', sa.Enum('AKTIF', 'DISEMBUNYIKAN', name='statuskomentar'), nullable=False),
    sa.Column('waktu_komentar', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_artikel'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['artikel_komentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artikel_komentar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artikel_komentar_id_artikel'), ['id_artikel'], unique=False)
        batch_op.create_index(batch_op.f('ix_artikel_komentar_id_user'), ['id_user'], unique=False)

    op.create_table('artikel_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_artikel', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('waktu_like', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_artikel'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_artikel', 'id_user', name='uq_artikel_user_like')
    )
    with op.batch_alter_table('artikel_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artikel_likes_id_artikel'), ['id_artikel'], unique=False)
        batch_op.create_index(batch_op.f('ix_artikel_likes_id_user'), ['id_user'], unique=False)

    op.create_table('tindak_lanjut_laporan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_laporan', sa.String(length=36), nullable=False),
    sa.Column('tindak_lanjut_penanganan', sa.String(length=200), nullable=False),
    sa.Column('tim_penindak', sa.String(length=200), nullable=True),
    sa.Column('foto_sebelum_tindakan_urls', sa.JSON(), nullable=True),
    sa.Column('foto_setelah_tindakan_urls', sa.JSON(), nullable=True),
    sa.Column('id_user_penindak', sa.String(length=36), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_laporan'], ['laporan_sampah_ilegal.id'], ),
    sa.ForeignKeyConstraint(['id_user_penindak'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tindak_lanjut_laporan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tindak_lanjut_laporan_id_laporan'), ['id_laporan'], unique=False)
        batch_op.create_index(batch_op.f('ix_tindak_lanjut_laporan_id_user_penindak'), ['id_user_penindak'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tindak_lanjut_laporan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tindak_lanjut_laporan_id_user_penindak'))
        batch_op.drop_index(batch_op.f('ix_tindak_lanjut_laporan_id_laporan'))

    op.drop_table('tindak_lanjut_laporan')
    with op.batch_alter_table('artikel_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artikel_likes_id_user'))
        batch_op.drop_index(batch_op.f('ix_artikel_likes_id_artikel'))

    op.drop_table('artikel_likes')
    with op.batch_alter_table('artikel_komentar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artikel_komentar_id_user'))
        batch_op.drop_index(batch_op.f('ix_artikel_komentar_id_artikel'))

    op.drop_table('artikel_komentar')
    with op.batch_alter_table('marketplace_daur_ulang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_daur_ulang_kategori_barang_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_daur_ulang_id_penjual'))

    op.drop_table('marketplace_daur_ulang')
    with op.batch_alter_table('laporan_sampah_ilegal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laporan_sampah_ilegal_jenis_sampah_id'))
        batch_op.drop_index(batch_op.f('ix_laporan_sampah_ilegal_id_warga'))

    op.drop_table('laporan_sampah_ilegal')
    with op.batch_alter_table('kolaborator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kolaborator_jenis_kolaborator_id'))
        batch_op.drop_index(batch_op.f('ix_kolaborator_id_user'))

    op.drop_table('kolaborator')
    with op.batch_alter_table('aset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aset_kategori_aset_id'))
        batch_op.drop_index(batch_op.f('ix_aset_id_user'))

    op.drop_table('aset')
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artikel_slug'))
        batch_op.drop_index(batch_op.f('ix_artikel_kategori_id'))
        batch_op.drop_index(batch_op.f('ix_artikel_id_penulis'))

    op.drop_table('artikel')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('ref_kategori_barang')
    op.drop_table('ref_kategori_aset')
    op.drop_table('ref_kategori_artikel')
    op.drop_table('ref_jenis_sampah')
    op.drop_table('ref_jenis_kolaborator')
    # ### end Alembic commands ###
