"""add all new models with reference tables

Revision ID: fa341cbd8ad6
Revises: 97f1bee357d7
Create Date: 2026-03-09 08:07:38.452982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa341cbd8ad6'
down_revision = '97f1bee357d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_jenis_kolaborator',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_jenis_sampah',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_kategori_artikel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_kategori_aset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ref_kategori_barang',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_artikel_kategori_id'), ['kategori_id'], unique=False)
        batch_op.create_foreign_key(None, 'ref_kategori_artikel', ['kategori_id'], ['id'])
        batch_op.drop_column('kategori')

    with op.batch_alter_table('aset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_aset_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_aset_kategori_aset_id'), ['kategori_aset_id'], unique=False)
        batch_op.create_foreign_key(None, 'ref_kategori_aset', ['kategori_aset_id'], ['id'])
        batch_op.drop_column('kategori_aset')

    with op.batch_alter_table('kolaborator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_kolaborator_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_kolaborator_jenis_kolaborator_id'), ['jenis_kolaborator_id'], unique=False)
        batch_op.create_foreign_key(None, 'ref_jenis_kolaborator', ['jenis_kolaborator_id'], ['id'])
        batch_op.drop_column('jenis_kolaborator')

    with op.batch_alter_table('laporan_sampah_ilegal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_sampah_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_laporan_sampah_ilegal_jenis_sampah_id'), ['jenis_sampah_id'], unique=False)
        batch_op.create_foreign_key(None, 'ref_jenis_sampah', ['jenis_sampah_id'], ['id'])
        batch_op.drop_column('jenis_sampah')

    with op.batch_alter_table('marketplace_daur_ulang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_barang_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_marketplace_daur_ulang_kategori_barang_id'), ['kategori_barang_id'], unique=False)
        batch_op.create_foreign_key(None, 'ref_kategori_barang', ['kategori_barang_id'], ['id'])
        batch_op.drop_column('kategori_barang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_daur_ulang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_barang', postgresql.ENUM('PLASTIK', 'KACA', 'LOGAM', 'KERTAS', 'ELEKTRONIK', name='kategoribarang'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_marketplace_daur_ulang_kategori_barang_id'))
        batch_op.drop_column('kategori_barang_id')

    with op.batch_alter_table('laporan_sampah_ilegal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_sampah', postgresql.ENUM('ORGANIK', 'PLASTIK', 'KACA', 'LOGAM', 'TEKSTIL', 'B3', 'CAMPURAN', name='jenissampah'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_laporan_sampah_ilegal_jenis_sampah_id'))
        batch_op.drop_column('jenis_sampah_id')

    with op.batch_alter_table('kolaborator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_kolaborator', postgresql.ENUM('KOMUNITAS', 'LSM', 'SEKOLAH', 'INSTANSI', 'CSR', name='jeniskolaborator'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kolaborator_jenis_kolaborator_id'))
        batch_op.drop_column('jenis_kolaborator_id')

    with op.batch_alter_table('aset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_aset', postgresql.ENUM('BANK_SAMPAH', 'TPA', 'COMPOSTING', 'KENDARAAN', 'TPST', name='kategoriaset'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_aset_kategori_aset_id'))
        batch_op.drop_column('kategori_aset_id')

    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', postgresql.ENUM('EDUKASI', 'BERITA', 'EVENT', 'OPINI', name='kategoriartikel'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_artikel_kategori_id'))
        batch_op.drop_column('kategori_id')

    op.drop_table('ref_kategori_barang')
    op.drop_table('ref_kategori_aset')
    op.drop_table('ref_kategori_artikel')
    op.drop_table('ref_jenis_sampah')
    op.drop_table('ref_jenis_kolaborator')
    # ### end Alembic commands ###
